fail_fast: false

repos:
  # TypeScript/JavaScript - Use local Biome (format + safe fixes only)
  - repo: local
    hooks:
      - id: fix-staged
        name: Runs formatter, linter and import sorting on staged files; applies safe fixes
        entry: npm
        args: [run, "fix:staged"]
        language: system
        pass_filenames: false
        require_serial: true

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type check
        entry: npm
        args: [run, check]
        language: system
        pass_filenames: false
        require_serial: true

  # Essential file validation (no formatting changes)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^(results|dist|node_modules|.*premade-pre-refactor)/
      - id: check-merge-conflict